package com.esprit.microservice.complaint;

public enum ComplaintCategory {
    RETARD_LIVRAISON,
    PRODUIT_ENDOMMAGE,
    MAUVAIS_SERVICE_CLIENT,
    ERREUR_FACTURATION,
    ARTICLE_MANQUANT,
    LIVRAISON_MAUVAISE_ADRESSE,
    COMMANDE_INCOMPLETE,
    MAUVAISE_QUALITE,
    COMPORTEMENT_PERSONNEL,
    PROBLEME_TECHNIQUE,
    PROBLEME_REMBOURSEMENT,
    FRAIS_INATTENDUS,
    PUBLICITE_MENSONGERE,
    SECURITE_HARCELEMENT,
    ADVERTISEMENT,  // New category specifically for ad reports
    AUTRE
}
